### ISSUE TITLE
Error response from daemon: login attempt to https://hub.docker.com/v2/ failed with status: 404 Not Found

### ISSUE THREAD

**Issue by zhaoqishan** [3kraft/docker-remote-deploy-action#1]
Why is the word v2 automatically added when I don't have it configured.
please tell me when you are free.

deploy:
    runs-on: ubuntu-latest
    needs: build    
    steps:
      - name: Run docker deployment
        uses: 3kraft/docker-remote-deploy-action@v1
        with:
          docker-host: ${{ secrets.HOST }}
          docker-host-user: ${{ secrets.USERNAME }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          registry: hub.docker.com 
          registry-user: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-token: ${{ secrets.DOCKERHUB_ACTION_TOKEN }}
          container-name: mfh_services01
          container-ports: '8000:80'
          image-name: '${{ secrets.DOCKERHUB_USERNAME }}/mfh_services01'
          tag-name: ${{ github.ref_name }}
          container-args: '-d --restart unless-stopped'

**Comment by jansolo** [comment]
`docker login` fails, when setting the default docker registry `hub.docker.com`. Remove the `registry` property from your action and login should work. I therefore removed the `required` and `default` flag from the `registry` property. You need to update your action to use Version `v1.1`.
